---
title: "houseprice_lu"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## R Markdown
 <http://rmarkdown.rstudio.com>.
```{r set.up.env.package}
setwd("~/Dropbox/nycdsa/projects/proj3_houseprice/lu")
# library for data wrangling & plotting
library(tidyverse);library(zeallot)
# library for data imputing
library(VIM);library(mice);library(caret);library(Hmisc)
# library for modeling
```

```{r load.data.set}
train = read_csv("./raw_data/train.csv")
test = read_csv("./raw_data/test.csv")
```

```{r check.NA}
# check what NA stands for and how to impute
train[!is.na(train$LotFrontage), c("LotFrontage", "LotArea", "Street")] %>% .[order(.$LotFrontage),] %>% View() 
train[is.na(train$LotFrontage), c("LotFrontage", "LotArea", "Street")] %>% .[order(.$LotFrontage),] %>% View() #So LotFrontage NA is due to LotArea 0, impute with 0
train[is.na(train$LotFrontage), ] %>% nrow()

train[is.na(train$Alley), "Alley" ] %>% View()

train[is.na(train$Exterior2nd), c("Exterior1st", "Exterior2nd")] %>% View()

train[is.na(train$MasVnrType), c('MasVnrType', 'MasVnrArea')] %>% View() # so MasVnrType NA & MasVnrArea NA are due to no masonry veneer, impute with "nothing" 

train[!is.na(train$Electrical), c("Electrical", "Utilities", "CentralAir", "HeatingQC", "Heating")] %>% View()

train[is.na(train$BsmtExposure) | is.na(train$BsmtFinType2),c("Id", "BsmtQual", "BsmtCond", "BsmtExposure", "BsmtFinType1", "BsmtFinSF1", "BsmtFinType2", "BsmtFinSF2","BsmtUnfSF","TotalBsmtSF")] %>% View() # id 949, BsmtExposure should be no, because it has all other basement features, NA here should not mean no basement, impute with "No", rest NA rows impute with Nothing; id 333, BsmtFinType2 is null, but has all other basement features, so here NA means no 2nd finish, but can still impute with Nothing

garage_rows = train[is.na(train$GarageType),c("Id", "YearBuilt", "GarageType","GarageYrBlt", "GarageFinish", "GarageQual", "GarageCond", "GarageCars", "GarageArea") ] %>% select(Id) %>% unlist() 
train[train$Id %in% garage_rows, c("Id", "YearBuilt", "GarageType","GarageYrBlt", "GarageFinish", "GarageQual", "GarageCond", "GarageCars", "GarageArea")] %>% View()

train[is.na(train$PoolQC), c("PoolArea", "PoolQC")] %>% View()

train[is.na(train$FireplaceQu), c("FireplaceQu", "Fireplaces")] %>% View()

train[is.na(train$Fence), "Fence"] %>% View()

train[is.na(train$MiscFeature), c("MiscFeature", "MiscVal")] %>% View()
```

```{r trim.and.impute}
train = apply(train, 2, function(x) tolower(x))
train = apply(train, 2, function(x) trimws(x))
train = as_tibble(train)

train$LotFrontage = impute(train$LotFrontage, 0)
train$Alley = impute(train$Alley, "nothing")

train$MasVnrType = impute(train$MasVnrType, "nothing")
train$MasVnrType = train$MasVnrType %>% str_replace_all("none", "nothing") 
train$MasVnrArea = impute(train$MasVnrArea, 0)

train$GarageYrBlt[is.na(train$GarageYrBlt)] = train$YearBuilt[is.na(train$GarageYrBlt)]
#train[is.na(train$GarageYrBlt), c("Id", "GarageYrBlt", "YearBuilt")]
#fill = train[is.na(train$GarageYrBlt), c("YearBuilt")]
#left_out = train[is.na(train$GarageYrBlt), c("Id")]
#train[is.na(train$GarageYrBlt), "GarageYrBlt"] = fill
#train[train$Id %in% left_out,c("Id", "GarageYrBlt", "YearBuilt")]
#train[train$MasVnrArea == 0, c("MasVnrType", "MasVnrArea")] %>% View()

# get_mode = function(x){
#   lv = unique(x)
#   ans = lv[which.max(tabulate(match(x, lv)))] %>% as.character()
#   return(ans)
# }

# get_mode(train$Electrical)
train$Electrical = impute(train$Electrical, "sbrkr")

train[949, "BsmtExposure"] = "no"
col_nothing = c("BsmtQual", "BsmtCond", "BsmtExposure", "BsmtFinType1", "BsmtFinSF1", "BsmtFinType2", "BsmtFinSF2","BsmtUnfSF","TotalBsmtSF")

# impute_nothing = function(column){
#   train[,column] = impute(train[,column], "nothing")
# }
# sapply(col_nothing, impute_nothing)

for (column in col_nothing){
  train[,column] = impute(train[,column], "nothing")
}

garage = c("GarageType", "GarageYrBlt", "GarageFinish", "GarageQual", "GarageCond", "GarageCars","GarageArea")

for (column in garage){
  train[,column] = impute(train[,column], "nothing")
}

train$PoolQC = impute(train$PoolQC, 'nothing')

train$FireplaceQu = impute(train$FireplaceQu, 'nothing')

train$Fence = impute(train$Fence, 'nothing')

train$MiscFeature = impute(train$MiscFeature, 'nothing')


## check NA
#missing <- which(colSums(is.na(train)) > 0)
#sort(colSums(sapply(train[missing], is.na)), decreasing=TRUE)
#str_detect(train, "none") %>% sum()
#str_detect(train, "na") %>% sum()
which(train == "none")
which(train == "na")
which(is.na(train))

write.csv(file = "./processed_data/train_full.csv", train)
```



```{r convert.ordinal}
#c(Typ, Min1, Min2, Mod, Maj1, Maj2, Sev, Sal) %<-% seq(1,8)
train = read_csv("./processed_data/train_full.csv")
train = train[,-1] # get rid of auto-index
col_class = sapply(train, class)
str(train)

train$Functional = sapply(train$Functional, function(x) switch(x, typ = 8, min1 = 7, min2 = 6, mod = 5, maj1 = 4, maj2 = 3, sev = 2, sal = 1))
train$LandSlope = sapply(train$LandSlope, function(x) switch(x, gtl = 3, mod = 2, sev = 1))
train$GarageFinish = sapply(train$GarageFinish, function(x) switch(x, fin = 3, rfn = 2, unf = 1, nothing = 0))
#train$Fence = sapply(train$Fence, function(x) switch(x, gdprv = 4, mnprv = 3, gdwo = 2, mnww = 1, nothing = 0))

switch_qual = function(x){
  sapply(x, function(y) switch(y, ex = 5, gd = 4, ta = 3, fa = 2, po = 1, nothing = 0))
}
switch_type = function(x){
  sapply(x, function(y) switch(y, glq = 6, alq = 5, blq = 4, rec = 3, lwq = 2, unf = 1, nothing = 0))
}
switch_exposure = function(x){
  sapply(x, function(y) switch(y, gd = 4, av = 3, mn = 2, no = 1, nothing = 0))
}

# 1st time missed: BsmtExposure, KitchenQual, BsmtCond - convert to ordinal

train$ExterQual = switch_qual(train$ExterQual)
train$ExterCond = switch_qual(train$ExterCond)
train$HeatingQC = switch_qual(train$HeatingQC)
train$KitchenQual = switch_qual(train$KitchenQual) # missed first time
train$BsmtQual = switch_qual(train$BsmtQual)
train$BsmtCond = switch_qual(train$BsmtCond) # missed the 1st time
train$BsmtExposure = switch_exposure(train$BsmtExposure) # missed the 1st time
train$BsmtFinType1 = switch_type(train$BsmtFinType1)
train$BsmtFinType2 = switch_type(train$BsmtFinType2)
train$GarageQual = switch_qual(train$GarageQual)
train$GarageCond = switch_qual(train$GarageCond)
train$PoolQC = switch_qual(train$PoolQC)
train$FireplaceQu = switch_qual(train$FireplaceQu)

# convert year to categorical
year_to_ordinal = function(year){
  decade = -1
  if (year < 1920) {
    decade = 1
  } else if (year > 1999){
    decade = 10
  }else{
    decade = ((year %/% 10 * 10) - 1900) / 10
  }
  return(decade)
}
#sapply(train$YearBuilt, year_to_ordinal)

train$YearBuilt = as.numeric(train$YearBuilt)
train$YearRemodAdd = as.numeric(train$YearRemodAdd)
train$GarageYrBlt = as.numeric(train$GarageYrBlt)

train$decade_YearBuilt = sapply(train$YearBuilt, year_to_ordinal)
train$decade_YearRemodAdd = sapply(train$YearRemodAdd, year_to_ordinal)
train$decade_GarageYrBlt = sapply(train$GarageYrBlt, year_to_ordinal)

str(train)

write_csv(train, "./processed_data/train_ordinal.csv")

# year_to_ordinal = function(year){
#   decade = -1
#   if (year < 1920) {
#     decade = 1
#   } else if (year > 1999){
#     decade = 10
#   }else{
#     decade = ((year %/% 10 * 10) - 1900) / 10
#   }
#   #return(decade)
#   paste0('group_',as.character(decade))
# }
```

```{r dummify}
library(rlang)
train = read_csv("./processed_data/train_full.csv")
train = train[,-1]

# train %>% get_dummies.(LandSlope, drop_first = T, dummify_na = F)
# train %>% get_dummies.(LandSlope, drop_first = T, dummify_na = F) %>% select(-LandSlope)
# train %>% get_dummies.(LandSlope, drop_first = F, dummify_na = F) %>% select(-LandSlope)

dummify = function(table, col){
  dummy = get_dummies.(table[,col], drop_first = F, dummify_na = F) %>% select(-!!col)
  # dummy = get_dummies.(table[,col], drop_first = T, dummify_na = F) %>% select(-!!col)
  # table %>% get_dummies.(table[,col], drop_first = T, dummify_na = F) %>% select(-!!col)
  cbind(select(train, -!!col), dummy) %>% as_tibble()
}
# class(train1), class(train2)
train = dummify(train, "LandSlope")
train = dummify(train, "GarageFinish")

# carat- dummify function, allow pass in multiple columns, learnig colnames from training set
# https://www.rdocumentation.org/packages/caret/versions/6.0-86/topics/dummyVars
```
